apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    type: pvc
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 250Mi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      type: pv
