---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections 64;}
    http {
      server {
          listen       8097;
          root   /var/www/html;
          location / {
              index  index.html index.htm index.php;
          }
      }
    }

