apiVersion: v1
kind: CronJob
meta:
  name: 
spec:
  schedule: "* */2 * * *"
  jobTemplate:
    spec:
      containers:
        - name: cron-xfusion
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          command:
            - echo "Welcome to xfusioncorp!""
        restartPolicy: OnFailure
