apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: xfusion 
spec:
  schedule: "* */11 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
           - name: cron-xfusion
             image: nginx:latest
             imagePullPolicy: IfNotPresent
             command:
             - /bin/sh
             - "-c"
             - "echo Welcome to xfusioncorp!"
          restartPolicy: OnFailure
