---
- name: Adduser ansible
  hosts: stapp01
  become: yes

  vars:
      passw_a: !vault
      passw_d: !vault
      pass_d: $6$6Lx08MUZ$6YAOJZqy4QSoYqZbaBIIirVumOZGsYRRkWIsoRH5S3dhx3.KUW0mbv1o0NgJ1Xdpsq.cBWxVtbzIZYwL7g1LE1
      pass_a: $6$6Lx08MUZ$6YAOJZqy4QSoYqZbaBIIirVumOZGsYRRkWIsoRH5S3dhx3.KUW0mbv1o0NgJ1Xdpsq.cBWxVtbzIZYwL7g1LE1

  tasks:
  - name: group admin create
    ansible.builtin.group:
      name: admins
      state: present

  - name: group developers create
    ansible.builtin.group:
      name: developers
      state: present

  - name: Create user adm1
    user:
      name: rob
      group: admins
      groups: wheel
      home: /home/rob
      password: "{{ pass_a }}"
      append: yes

  - name: Create user adm2
    user:
      name: david
      group: admins
      groups: wheel
      home: /home/david
      password: "{{ pass_a }}"
      append: yes

  - name: Create user adm3
    user:
      name: joy
      group: admins
      groups: wheel
      home: /home/joy
      password: "{{ pass_a }}"
      append: yes

  - name: Create user dev1
    user:
      name: tim
      group: developers
      home: /var/www
      password: "{{ pass_d }}"

  - name: Create user dev2
    user:
      name: ray
      group: developers
      home: /var/www
      password: "{{ pass_d }}"

  - name: Create user dev3
    user:
      name: jim
      group: developers
      home: /var/www
      password: "{{ pass_d }}"

  - name: Create user dev4
    user:
      name: mark
      group: developers
      home: /var/www
      password: "{{ pass_d }}"

# vault_password_file = ~/playbooks/secrets/vault.txt

# cat ~/playbooks/secrets/vault.txt   ansible-vault encrypt_string --stdin-name "some_name" # input encrypt pass # input string to crypt   
# ctrl + d

